const UNAUTHORIZED = 'UNAUTHORIZED'
const NO_TOKEN = 'NO_TOKEN'
const JWT_SECRET = 'JehovaIsOurGod'
const NO_EMAIL_VALID = 'NO_EMAIL_VALID'
const PASSWORD_WRONG = 'PASSWORD_WRONG'

export { UNAUTHORIZED, NO_TOKEN, JWT_SECRET, NO_EMAIL_VALID, PASSWORD_WRONG }
